# Generated by Django 3.2 on 2021-05-06 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='recomendate_medicine',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='recomendation',
            field=models.TextField(blank=True),
        ),
    ]
