# Generated by Django 3.2 on 2021-05-08 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_auto_20210506_0348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='date',
            new_name='date_of_creation',
        ),
        migrations.AddField(
            model_name='history',
            name='date_of_consult',
            field=models.DateTimeField(null=True),
        ),
    ]
